name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Quizzical Beats are you running?
      options:
        - Latest (main branch)
        - v1.9 (Security Hardening)
        - v1.8 (Documentation Dynamo)
        - v1.7 (Dropbox Dispatch)
        - v1.6 (Bulletproof Backups)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running Quizzical Beats?
      options:
        - Docker Compose (recommended)
        - Docker (custom)
        - Manual installation (pip)
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Provide relevant environment information:
        - OS (e.g., Ubuntu 22.04, macOS 13, Windows 11)
        - Python version (e.g., 3.11)
        - Browser (if web UI issue)
        - Database (SQLite, PostgreSQL, MySQL)
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.5
        - Browser: Chrome 120
        - Database: SQLite
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code.
        **Security Note**: Remove any API keys, tokens, or personal information!
      render: shell
      placeholder: |
        Paste logs here...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have removed any sensitive information (API keys, passwords, etc.) from logs and screenshots
          required: true
        - label: I am using a supported version of Quizzical Beats
          required: true
